### ISSUE TITLE
sqlite3 not working with android_new

### ISSUE THREAD

**Issue by tito** [kivy/python-for-android#1053]
@ngala commented on [Fri Jan 13 2017](https://github.com/kivy/buildozer/issues/457)

Before raising the issue, I have tried to refer any old issues with similar problems. Making attempts to work out solutions.

The Kivy App is running fine on the setup(Ubuntu 15.04 VM). The app was basic and did not have any other python libraries. I could successfully create an APK file and the App worked same on Android(Nexus 5x, Nougat 7.1.1) as it did on Ubuntu.

Now when I tried to import sqlite3, it worked fine on Ubuntu but it crashed on the phone. I was getting `no module named sqlite3` in my logcat.

On some digging,  I referred to https://github.com/kivy/kivy/issues/705
I removed the blacklisted files referring to sqlite3(including both sqlite3/* and lib-dynload/_sqlite3.so) from blacklist.txt and also installed libsqlite3-dev package. The error changed slightly... `no module named _sqlite3`

Apparently solution in that issue was partially applicable to new toolchain.

I went a step further and deleted .buildozer folder completely so that it would download and install packages in case they are broken.

but that did not resolve the issue...now it is getting compiler error

```
checking machine type as reported by uname -m... x86_64
checking for --without-gcc... no
checking for arm-eabi-gcc... /usr/bin/ccache arm-linux-androideabi-gcc -DANDROID -mandroid -fomit-frame-pointer --sysroot /home/droid/.buildozer/android/platform/android-ndk-r9c/platforms/android-19/arch-arm
checking whether the C compiler works... no
configure: error: in `/home/droid/andr/.buildozer/android/platform/build/build/other_builds/python2-sqlite3/armeabi-v7a/python2':
configure: error: C compiler cannot create executables
See `config.log' for more details
```
here's the complete file for buildozer debug output (http://pastebin.com/ANuYTu8R) and config.log(http://pastebin.com/maWgbBpw)

The apps created without sqlite3 are still working fine on both Ubuntu and Android.

---

@ngala commented on [Tue Feb 28 2017](https://github.com/kivy/buildozer/issues/457#issuecomment-282973446)

Hi...any update in this?

---

@tito commented on [Mon May 15 2017](https://github.com/kivy/buildozer/issues/457#issuecomment-301349920)

I think that's an issue with python-for-android directly. The recipe build order put sqlite3 after compiling Python, but it should been done before. I'm moving it.

**Comment by germn** [comment]
Duplicate https://github.com/kivy/python-for-android/issues/977

Solution [is](https://github.com/kivy/python-for-android/issues/977#issuecomment-292723081) to replace `hostpython2` with `python2` in requirements.

**Comment by ngala** [comment]
I am already using `hostpython2`. Please refer to line 60 in buildozer debug output (http://pastebin.com/ANuYTu8R). It suggests that hostpython2 is already being used.

Please let me know any other details are required for the resolution.

**Comment by germn** [comment]
@ngala 

> I am already using `hostpython2`

And you need to replace it with `python2` to get `sqlite3` working.

Your requirements should be: `python2, sqlite3, kivy`

**Comment by ngala** [comment]
That doesn't work either. By using python2, I was succesfuly able to create apk. However, I got runtime error while importing sqlite3.

For this specific issue, I created a small app for testing sqlite3 - https://pastebin.com/spZqk6pb

as per app, it will only import sqlite3 when we click on button. On clicking we get following traceback output after using `python2, sqlite3, kivy` in requirement:

```
06-01 16:15:24.762  4648  4772 I python  :  Traceback (most recent call last):
06-01 16:15:24.763  4648  4772 I python  :    File "/home/droid/andr/.buildozer/android/app/main.py", line 25, in imp_sqlite
06-01 16:15:24.763  4648  4772 I python  :    File "/home/droid/andr/.buildozer/android/platform/build/build/other_builds/python2/armeabi-v7a/python2/python-install/lib/python2.7/sqlite3/__init__.py", line 24, in <module>
06-01 16:15:24.764  4648  4772 I python  :    File "/home/droid/andr/.buildozer/android/platform/build/build/other_builds/python2/armeabi-v7a/python2/python-install/lib/python2.7/sqlite3/dbapi2.py", line 27, in <module>
06-01 16:15:24.765  4648  4772 I python  :  ImportError: No module named _sqlite3
```

It works on Ubuntu when i run "python2 main.py"

**Comment by FreakJoe** [comment]
Could you post your complete buildozer.spec file? Or at least relevant parts of it?

**Comment by ngala** [comment]
[app]

# (str) Title of your application
title = My Application

# (str) Package name
package.name = myapp

# (str) Package domain (needed for android/ios packaging)
package.domain = org.test

# (str) Source code where the main.py live
source.dir = .

# (list) Source files to include (let empty to include all the files)
source.include_exts = py,png,jpg,kv,atlas

# (list) List of inclusions using pattern matching
#source.include_patterns = assets/*,images/*.png

# (list) Source files to exclude (let empty to not exclude anything)
#source.exclude_exts = spec

# (list) List of directory to exclude (let empty to not exclude anything)
#source.exclude_dirs = tests, bin

# (list) List of exclusions using pattern matching
#source.exclude_patterns = license,images/*/*.jpg

# (str) Application versioning (method 1)
version = 0.1

# (str) Application versioning (method 2)
# version.regex = __version__ = ['"](.*)['"]
# version.filename = %(source.dir)s/main.py

# (list) Application requirements
# comma seperated e.g. requirements = sqlite3,kivy
requirements = kivy

# (str) Custom source folders for requirements
# Sets custom source for any requirements with recipes
# requirements.source.kivy = ../../kivy

# (list) Garden requirements
#garden_requirements =

# (str) Presplash of the application
#presplash.filename = %(source.dir)s/data/presplash.png

# (str) Icon of the application
#icon.filename = %(source.dir)s/data/icon.png

# (str) Supported orientation (one of landscape, portrait or all)
orientation = landscape

# (list) List of service to declare
#services = NAME:ENTRYPOINT_TO_PY,NAME2:ENTRYPOINT2_TO_PY

#
# OSX Specific
#

#
# author = © Copyright Info

#
# Android specific
#

# (bool) Indicate if the application should be fullscreen or not
fullscreen = 1

# (list) Permissions
#android.permissions = INTERNET

# (int) Android API to use
#android.api = 19

# (int) Minimum API required
#android.minapi = 9

# (int) Android SDK version to use
#android.sdk = 20

# (str) Android NDK version to use
#android.ndk = 9c

# (bool) Use --private data storage (True) or --dir public storage (False)
#android.private_storage = True

# (str) Android NDK directory (if empty, it will be automatically downloaded.)
#android.ndk_path =

# (str) Android SDK directory (if empty, it will be automatically downloaded.)
#android.sdk_path =

# (str) ANT directory (if empty, it will be automatically downloaded.)
#android.ant_path =

# (str) python-for-android git clone directory (if empty, it will be automatically cloned from github)
#android.p4a_dir =

# (list) python-for-android whitelist
#android.p4a_whitelist =

# (bool) If True, then skip trying to update the Android sdk
# This can be useful to avoid excess Internet downloads or save time
# when an update is due and you just want to test/build your package
# android.skip_update = False

# (str) Android entry point, default is ok for Kivy-based app
#android.entrypoint = org.renpy.android.PythonActivity

# (list) List of Java .jar files to add to the libs so that pyjnius can access
# their classes. Don't add jars that you do not need, since extra jars can slow
# down the build process. Allows wildcards matching, for example:
# OUYA-ODK/libs/*.jar
#android.add_jars = foo.jar,bar.jar,path/to/more/*.jar

# (list) List of Java files to add to the android project (can be java or a
# directory containing the files)
#android.add_src =

# (str) python-for-android branch to use, if not master, useful to try
# not yet merged features.
#android.branch = master

# (str) OUYA Console category. Should be one of GAME or APP
# If you leave this blank, OUYA support will not be enabled
#android.ouya.category = GAME

# (str) Filename of OUYA Console icon. It must be a 732x412 png image.
#android.ouya.icon.filename = %(source.dir)s/data/ouya_icon.png

# (str) XML file to include as an intent filters in <activity> tag
#android.manifest.intent_filters =

# (list) Android additionnal libraries to copy into libs/armeabi
#android.add_libs_armeabi = libs/android/*.so
#android.add_libs_armeabi_v7a = libs/android-v7/*.so
#android.add_libs_x86 = libs/android-x86/*.so
#android.add_libs_mips = libs/android-mips/*.so

# (bool) Indicate whether the screen should stay on
# Don't forget to add the WAKE_LOCK permission if you set this to True
#android.wakelock = False

# (list) Android application meta-data to set (key=value format)
#android.meta_data =

# (list) Android library project to add (will be added in the
# project.properties automatically.)
#android.library_references =

# (str) Android logcat filters to use
#android.logcat_filters = *:S python:D

# (bool) Copy library instead of making a libpymodules.so
#android.copy_libs = 1

#
# iOS specific
#

# (str) Path to a custom kivy-ios folder
#ios.kivy_ios_dir = ../kivy-ios

# (str) Name of the certificate to use for signing the debug version
# Get a list of available identities: buildozer ios list_identities
#ios.codesign.debug = "iPhone Developer: <lastname> <firstname> (<hexstring>)"

# (str) Name of the certificate to use for signing the release version
#ios.codesign.release = %(ios.codesign.debug)s


[buildozer]

# (int) Log level (0 = error only, 1 = info, 2 = debug (with command output))
log_level = 2

# (int) Display warning if buildozer is run as root (0 = False, 1 = True)
warn_on_root = 1

# (str) Path to build artifact storage, absolute or relative to spec file
# build_dir = ./.buildozer

# (str) Path to build output (i.e. .apk, .ipa) storage
# bin_dir = ./bin

#    -----------------------------------------------------------------------------
#    List as sections
#
#    You can define all the "list" as [section:key].
#    Each line will be considered as a option to the list.
#    Let's take [app] / source.exclude_patterns.
#    Instead of doing:
#
#[app]
#source.exclude_patterns = license,data/audio/*.wav,data/images/original/*
#
#    This can be translated into:
#
#[app:source.exclude_patterns]
#license
#data/audio/*.wav
#data/images/original/*
#


#    -----------------------------------------------------------------------------
#    Profiles
#
#    You can extend section / key with a profile
#    For example, you want to deploy a demo version of your application without
#    HD content. You could first change the title to add "(demo)" in the name
#    and extend the excluded directories to remove the HD content.
#
#[app@demo]
#title = My Application (demo)
#
#[app:source.exclude_patterns@demo]
#images/hd/*
#
#    Then, invoke the command line with the "demo" profile:
#
#buildozer --profile demo android debug

**Comment by ngala** [comment]
buildozer.spec - https://pastebin.com/zF9K12qd

**Comment by FreakJoe** [comment]
Try actively whitelisting files required for sqlite3 in your buildozer.spec, like so:
`android.p4a_whitelist = encodings/cp1252.pyo,sqlite3/*,lib-dynload/_sqlite3.so`

That, along with adding sqlite3 to the requirements and running `buildozer android_new clean` before my next build fixed all issues I had with sqlite3 (and sqlalchemy).

**Comment by ngala** [comment]
I am successfully able to import sqlite3 after performing the above 2 steps.

Thanks it works now.

**Comment by inclement** [comment]
sqlite3 is currently working well in the master branch.
