### ISSUE TITLE
Can p4a be used without a bootstrap?

### ISSUE THREAD

**Issue by frmdstryr** [kivy/python-for-android#1055]
I just want to cross compile a python distribution and include it in an existing android project.  Is this possible?

**Comment by inclement** [comment]
p4a's api requires targeting a bootstrap, but this is actually compatible with what you want since a bootstrap is just a java android project with the python stuff prebuilt. The `service_only` bootstrap is ideal, as it doesn't by default build anything except python itself.

After building such a bootstrap, you can extract  the python project with something like `p4a export-dist --dist-name "yourdistname" output_dir`, then copy everything you need from there. You'd also need to replicate some of the unpacking that p4a does, I can give some suggestions about that if it isn't clear to you how to do so.

If you just need Python itself, a simple alternative is to use the CrystaX NDK.
