### ISSUE TITLE
Kivy App Crashes Immediately on Android

### ISSUE THREAD

**Issue by raythenewuser** [kivy/python-for-android#1128]
Hello All,

I have developed a very simple app with Kivy & KivyMD and everything works fine on my computer. Even the build for android (command: buildozer android debug) works perfectly fine on my computer, but the app crashes immediately after running on Android. I seem not to be able to find out what the problem is. I have attached both buildozer.spec (I had to change it to buildozer.txt to upload) and logcat.txt for your review. Please help.

PS. I used buildozer 0.33 on the Kivy VM 2.0
PS2. I am using python 3.6.2 with Pycharm IDE on Win 10

[buildozer.txt](https://github.com/kivy/python-for-android/files/1345610/buildozer.txt)
[logcat.txt](https://github.com/kivy/python-for-android/files/1345609/logcat.txt)

**Comment by inclement** [comment]
Use `adb logcat` to view the traceback on the device, as described in the [documentation](https://kivy.org/docs/guide/android.html#debugging-your-application-on-the-android-platform). Your `logcat.txt` does not seem to show the logcat log from the device, only the build log.

If you can't find the problem in the logcat log, please post the full details (including that log) on the [kivy-users mailing list](https://groups.google.com/forum/#!forum/kivy-users), as we normally use github issues only for actual bug reports. You can open a bug report later if the problem turns out to be an issue with python-for-android.
