### ISSUE TITLE
assert keyword do not work

### ISSUE THREAD

**Issue by Fogapod** [kivy/python-for-android#1193]
I saw [this](https://github.com/qpython-android/qpython/issues/46) issue first and decided to check if this problem occurs in other ~~kivy~~ python implementations on Android. Assert did not work for me in apps builded with various versions of p4a (from old toolchain to 0.6.0)
Syntax `assert False` is ignored in any kivy app on Android (not sure for python3 builds though)
I assume the the problem is somewhere in the python build process

**Comment by tito** [comment]
Because p4a ship compiled version (optimized?) of Python bytecode (-OO). This removes the assert and code behind `__debug__`. You can consider it as "release" code shipped into the APK.

Now that you mention it, i guess it would be nice to do that only for the actual release, and not debug mode.

@inclement ?

**Comment by inclement** [comment]
That would make sense to me. I'm not sure the -OO affects the size much anyway.

**Comment by inclement** [comment]
I made a PR at https://github.com/kivy/python-for-android/pull/1221 that should fix this, but haven't tested it yet other than to make sure the compiling works.
