### ISSUE TITLE
When you fix the error "error: [Errno 2] No such file or directory: 'src/main/assets/private.mp3'"

### ISSUE THREAD

**Issue by HeaTTheatR** [kivy/python-for-android#1279]
Install python-for-android:

```python
pip install git+https://github.com/kivy/python-for-android.git
```

Building the project ends with an error:

```python
error: [Errno 2] No such file or directory: 'src/main/assets/private.mp3'
```

You have this error for a long time. And, despite the fact that you say that you corrected it, it still appears.

**Comment by inclement** [comment]
Thanks for the bug report. I don't remember the details of this error, do you have a link to what I had thought corrected it?

**Comment by inclement** [comment]
I just discussed this error with someone, and I suspect the real problem is that the `assets` directory is not created, and that the `src/main/res/drawable` directory probably isn't either. I'm not sure why though, p4a definitely has code that tries to create them, and I haven't been able to reproduce it.

**Comment by HeaTTheatR** [comment]
I switched to an assembly with Python 3 (it works).So I do not see the point of suffering with Python 2

**Comment by AndreMiras** [comment]
is this fixed with https://github.com/kivy/python-for-android/pull/1262 and dup of #1257 ?

**Comment by inclement** [comment]
Looks like it should be, thanks for pointing it out @AndreMiras
