### ISSUE TITLE
Android: python startup complaining about missing hashlib functions

### ISSUE THREAD

**Issue by karolyi** [kivy/python-for-android#1293]
Referring to #1260, as that issue is closed for no apparent reason:

Python will complain about missing hashlib functionalities with a couple of tracebacks at the app startup, which is visible looking at logcat logs. While the tracebacks signal a problem that would normally make the program to exit if unhandled, in this case it's more informal, despite it looking scary. The application will start and run, it's just signaling that a library it uses, is missing the searched hashlib functions.

Leaving this open, until the issue will get fixed.

Pulling in @inclement

**Comment by inclement** [comment]
I think we're looking to merge https://github.com/kivy/python-for-android/pull/1217 rather than #1260. My most recent thoughts are there, and it's the next thing I intend to work on when i have some p4a time.

I think these messages are genuinely warnings rather than errors, and to be expected without openssl, so I'm closing the issue. Thanks for reporting it though.
