### ISSUE TITLE
'import lzma' fails with Python 3

### ISSUE THREAD

**Issue by JonasT** [kivy/python-for-android#1336]
`import lzma` fails with Python 3:

```
08-24 20:34:43.881  2066  2227 I python  : Traceback (most recent call last):
08-24 20:34:43.885  2066  2227 I python  :   File "./app.py", line 10, in <module>
08-24 20:34:43.886  2066  2227 I python  :     import lzma
08-24 20:34:43.886  2066  2227 I python  :   File "/mnt/expand/ccbe4e94-5878-4053-8382-d825486cc844/user/0/org.example.myapp/files/app/crystax_python/stdlib.zip/lzma.py", line 26, in <module>
08-24 20:34:43.888  2066  2227 I python  : ImportError: No module named '_lzma'
```
Do I need to install some dependency? Isn't this normally part of the standard library that should be included in any case? Not sure what to make of this

**Comment by AndreMiras** [comment]
Hi @JonasT,
Thank you for the bug report and debug log.
I haven't checked it myself, but you mentioned https://github.com/kivy/python-for-android/pull/786#issuecomment-415852751 that you had issue with lzma and you eventually got your app working. Did you workaround the lzma import issue or did you fix it?

I made a quick check on Ubuntu and yes lzma module seems to be part of the standard Python3 library:
```
$ dpkg -S _lzma*.so
libpython3.6-stdlib:amd64: /usr/lib/python3.6/lib-dynload/_lzma.cpython-36m-x86_64-linux-gnu.so
```
Apparently since Python 3.3 https://docs.python.org/3/library/lzma.html
So not sure why it's not shipped in Crystax Python3. It could be an upstream bug.
I'm wondering if we could workaround it with http://pypi.python.org/pypi/lzmaffi
Please keep us posted if you have more info.

**Comment by JonasT** [comment]
I rewrote my entire save format, in part because LZMA is also pretty slow (which is even more of an issue on mobile devices), so nope, didn't fix it :man_shrugging: and yeah, it might be an upstream bug

**Comment by JonasT** [comment]
WIth python3crystax gone this is now obsolete
