### ISSUE TITLE
Tech debt: webview, pygame and service_only bootstraps are hardwired to Python 2.7

### ISSUE THREAD

**Issue by JonasT** [kivy/python-for-android#1497]
The `Android.mk` Makefiles of all bootstraps other than `sdl2` are hardwired to link/include Python 2.7 files. We should fix that at some point (or remove the bootstraps no longer used/properly supported by anyone anyway)

**Comment by JonasT** [comment]
Also an additional note: the pygame bootstrap also seems to hardcode api level 14 and some other horrible things, it looks like it's in quite a bad shape. Are people still using this, does it even work in its current state with Python 2.7, and what's the plan for the future for the pygame bootstrap?

**Comment by inclement** [comment]
My plan for pygame is to just ignore it and eventually remove it if it becomes clearly broken. We seem to have succeeded quite well at getting people to not use it, so maybe we're already at that point. Please feel free to ignore it, or indeed propose removing it, rather than wasting effort on it.

**Comment by JonasT** [comment]
I personally don't care much for `pygame`, but that's easy for me to say since I don't use it. Maybe it would be a good idea to get some statistics or ask some users? (is there a good way of doing that?)

As for the others, I agree they might be useful. Maybe a good idea would be to have testapps to be built for them, which might help with at least doing a conscious test if stuff is broken in the future (beyond just relying on travis). Are there any around that can be actually run afterwards?

**Comment by inclement** [comment]
About pygame, it's actually easier than having to check if people use it because it's basically a Kivy-only legacy bootstrap. I think it might be able to run pygame apps, but they probably don't work well, e.g. I don't know if they can actually receive touches (Kivy uses a special mouse provider on that bootstrap). Since it's deprecated for Kivy's use, that's the only important thing when deciding to remove it or not. As you say, it has weird hardcoded values that probably make it not usable on the Play store any more anyway.

**Comment by JonasT** [comment]
Oh yeah I highly doubt you can build it on a >20 api level, which should make it unusable for play store for sure

**Comment by JonasT** [comment]
I'm closing this since I'm 99% sure @opacam fixed this (let me know if this is wrong and I'll reopen)
