### ISSUE TITLE
How do I use this software?

### ISSUE THREAD

**Issue by vivianfrench2** [kivy/python-for-android#1606]
I can't figure out how to use this software. I have Python code already saved. I just want to use it to create an application. Thank you.

**Comment by JonasT** [comment]
Have a look around here: https://python-for-android.readthedocs.io/en/latest/quickstart/ and if you use Python 3, I recommend to install from github/master as it says there.

However, if you have questions, the best is to email to the kivy-users or python-for-android mailing list, or come into the #support discord channel as seen here: https://github.com/kivy/python-for-android

I will close this for now since this bug tracker is mainly meant for bug reports and feature requests, and not really ideal for support help
