### ISSUE TITLE
weird orientation behavior

### ISSUE THREAD

**Issue by zworkb** [kivy/python-for-android#1698]
with a current p4 master checkout and the python3 recipe I encounter a strange behavior concerning the app orientation on the device:

- when the orientation is set to portrait the app behaves as expected
- when orientation=landscape the app starts as expected until I come into the python code, then the app suddenly rotates 180 degrees and the app stands upside-down.
- also trying other orientation (reverseLandscape, fullSensor) settings did not help, in those cases tha app switches to portrait mode.

Thanks
Philipp

**Comment by N43j** [comment]
I have a similar problem when launching my application on my Android phone.

Whether I set “orientation” (to portrait) in the p4a options or not, my app goes to landscape mode, whatever I do.

I’m also using Python 3 and the master version of Python for Android, plus Kivy 1.10.1, Android API 28 and NDK r17c. I’m on Windows and using Windows subsystem for Ubuntu 18.04.

My app used to work fine, but a few days I go I did a full reinstallation. Since then I’m struggling to build a working application.

**Comment by OptimusGREEN** [comment]
Have you tried using kivy master also?

**Comment by N43j** [comment]
Yes (that’s what I meant by “the master version of Python for Android”).

**Comment by OptimusGREEN** [comment]
you said you're using kivy 1.10.1, try adding kivy==master to your requirements.

**Comment by N43j** [comment]
Ah! sorry, I misread… Thought you were talking about p4a. My bad. (It’s getting late, I’m a bit tired.)

I tried first with only “kivy” in the requirements (instead of “kivy==1.10.1”). Same behaviour.

Then I tried with “kivy==master”. Now my app crashes on start… adb gives me this error:

02-12 23:16:49.418 23382 23402 I python  : [CRITICAL] [Window      ] Unable to find any valuable Window provider.
02-12 23:16:49.418 23382 23402 I python  : sdl2 - Exception: Unknown <png> type, no loader found.

I saw that there was an issue ([#6134](https://github.com/kivy/kivy/issues/6134)) about it, but it looks like the problem is solved, so I don’t know what to do about it.

**Comment by tito** [comment]
Just compiled with latest p4a master, got the issue :/
"* when orientation=landscape the app starts as expected until I come into the python code, then the app suddenly rotates 180 degrees and the app stands upside-down." < exactly

**Comment by bavrock** [comment]
> I have a similar problem when launching my application on my Android phone.
> 
> Whether I set “orientation” (to portrait) in the p4a options or not, my app goes to landscape mode, whatever I do.
> 

same problem after p4a update :(

**Comment by JonasT** [comment]
@tito @everyoneelse just to make it clear, this is expected behavior when using a kivy **older** than this commit https://github.com/kivy/kivy/commit/b0befbe606d42fc34a1502d12e484c3980bd1495 with a p4a with this commit or **newer**: https://github.com/kivy/python-for-android/commit/16b07eda580d60ed417ffe18992c44132c1f8f79

This is because old SDL2 ignored kivy always requesting landscape mode even when the app started up differently (which kivy did due to a bug), and 2.0.9 actually reacts to this breaking things in the process (so kivy needed to be updated to fix this).

So this is why `kivy==master` is required to fix this unless a kivy release with the commit above was already done, I'm not completely up to date on the kivy releases since I personally don't use it

**Comment by JonasT** [comment]
Also if you want to use `sensor` orientation, you'll need an even newer kivy with this commit or newer: https://github.com/kivy/kivy/commit/775cd9e6e39809ad52de10280a5aa8d76c56a24c

Not sure what the state with `user` orientation is, but sensor & portrait & landscape should work fine if your kivy is new enough. (If `user` doesn't then it probably needs a similar fix as the sensor one in that particular commit)

**Comment by JonasT** [comment]
Follow-up from chat: https://github.com/kivy/kivy/pull/6163 this could also possibly the issue here, I just made an assumption that might be wrong about another recent change regarding orientations

**Comment by bavrock** [comment]
kivy==master --> orientation is OK --> but no FULLSCREEN mode (.spec fullscreen=1)

**Comment by AndreMiras** [comment]
The `kivy` recipe is already running on a version more recent than the last release, see https://github.com/kivy/python-for-android/blob/999df75/pythonforandroid/recipes/kivy/__init__.py
It's currently running on this commit https://github.com/kivy/kivy/commit/a95d67fde782cec52f01d4207690fe4070aec4d3 does it need to be update to an even more recent version?

**Comment by guysoft** [comment]
Ineed, fullscreen has a crazy refresh rate with ``kivy==master`` can confirm on my end too.

**Comment by inclement** [comment]
Just merged a fix for the orientation issue.

**Comment by inclement** [comment]
@guysoft Is there already a different issue for the fullscreen refresh? I'm not clear what the problem is.
