### ISSUE TITLE
Fullscreen mode does not work

### ISSUE THREAD

**Issue by bavrock** [kivy/python-for-android#1724]
### Versions

* Python: 3
* OS: Xubuntu 18.10, Android
* Kivy: master
* Cython: 0.28.2

### Description
Spec file:
p4a.branch = master
fullscreen = 1
kivy==master

But the application does not start in full screen mode! Status bar visible!

**Comment by inclement** [comment]
Thanks for the report, will look into it. It's possible something else has been missed in the sdl2 upgrade.

**Comment by JonasT** [comment]
@bavrock do you still have this issue with the latest p4a release? there have been a few additional updates regarding this that should hopefully fix things

**Comment by bavrock** [comment]
OK 👍

**Comment by bavrock** [comment]
Oh, no :(
orientation = sensorLandscape is WORK,
but orientation = all or portrait NOT start in full screen mode! Status bar visible!

**Comment by Ham-Merhead** [comment]
Oh, no, indeed :(

--orientation landscape  PASS
--orientation portrait      FAIL
--orientation sensor        FAIL

both the FAIL cases result in 'orientation landscape' with a status bar, and a navigation bar
the PASS case does not have a status bar 

This worked two months ago:
https://github.com/kivy/python-for-android/issues/1117#issuecomment-461231727

[log_portrait.txt](https://github.com/kivy/python-for-android/files/3087822/log_portrait.txt)
[log_sensor.txt](https://github.com/kivy/python-for-android/files/3087823/log_sensor.txt)
[log_landscape.txt](https://github.com/kivy/python-for-android/files/3087824/log_landscape.txt)
[p4a.txt](https://github.com/kivy/python-for-android/files/3087829/p4a.txt)

**Comment by inclement** [comment]
I'm not 100% sure your build is using kivy master, did you clean and 
rebuild after adding the `==master` in the --requirements line?

But, if you are using kivy master, this looks like a bug. From the log, 
setOrientation is being called with landscape parameters, which 
specifically should not happen in Kivy master.

You could also try setting the KIVY_ORIENTATIONS environment variable to 
the empty string, although again this should only be necessary as a 
workaround on kivy not-master.

**Comment by Ham-Merhead** [comment]
I was not using master. After clean_all, I ran another build that does not request master, then ran this build which does request master -- but I didn't get Kivy master. A bug perhaps, but not for this thread.

So I redo without the other build: "Clean_all, p4a Kivy==master"  Ran full build today.

Using the same app as I used in the other tread. I get run time crash, log attached. 

```
from kivy.app import App
from kivy.uix.label import Label
from kivy.graphics import Color, Rectangle
from kivy.core.window import Window

class Demo(App):
    def set_background_color(self):
        with self.label.canvas.before:
            Color(0.5, 0.0, 0.5)
            Rectangle(size=Window.size) 
       
    def _resize_handler(self,obj,size):
        self.set_background_color()

    def build(self):
        foo = Window.size
        Window.bind(size=self._resize_handler)
        self.label = Label(text = 'Greetings Earthlings')
        self.set_background_color()
        return self.label

if __name__ == '__main__':
    Demo().run()

```
Crashes here because Window is not defined.
```
    def build(self):
        foo = Window.size
```


From log file :
```
04-17 15:12:27.060  9820  9842 E libEGL  : validate_display:92 error 3008 (EGL_BAD_DISPLAY)
04-17 15:12:27.060  9820  9842 V SDL     : setOrientation() orientation=-1 width=1080 height=2160 resizable=true hint=
```

and later

`04-17 15:12:27.148  9820  9842 I python  : [CRITICAL] [Window      ] Unable to find any valuable Window provider.`

Pilot error (again) or something else?


[log_sensor_2.txt](https://github.com/kivy/python-for-android/files/3092197/log_sensor_2.txt)

**Comment by inclement** [comment]
Hmm, the good news is that the setOrientation call looks correct now. the bad news is that I'm not sure what's wrong with the build, the error generally indicates that the compiled parts of Kivy are for the wrong architecture or missing entirely, but I'm not aware of any current issues that would cause that, especially since you had it running before. Could you post the full logcat output?

**Comment by Ham-Merhead** [comment]
The logcat was attached log_sensor_2.txt

**Comment by inclement** [comment]
Then I don't know what's wrong. Does it work if you run a trivial testapp with this build, rather than your full app?

**Comment by Ham-Merhead** [comment]
I'm just running the (to me) simple test app listed above.
I will clean and re-install, maybe ....
Thanks for your help

**Comment by Ham-Merhead** [comment]
Reinstalled p4a, deleted ~/.android ~/.cache ~/.gradle, and power cycled the phone; 
Better but new problem:

--orientation landscape  PASS
--orientation portrait      PASS
--orientation sensor       FAIL
It crashes intermittently on a rotate, within the first few rotates.
Logcat attached
The tail of the backtrace says:
```
04-18 10:09:30.879 11590 11590 F DEBUG   :     #07 pc 000080e3  /data/data/com.example.ex/files/app/_python_bundle/site-packages/kivy/graphics/vbo.so
04-18 10:09:30.884   621   621 E libc    : Access denied finding property "vendor.debug.egl.swapinterval"
```
'Egl' again ! 
Looked in Kivy/graphics/vbo files - no reference to swapinterval 
 Btw, the phone is a Pixel3 which is fairly mainstream, it has no other issues.
My friend Google had lots of information, but no help.

Any suggestions?

[log_file4.txt](https://github.com/kivy/python-for-android/files/3096039/log_file4.txt)

**Comment by inclement** [comment]
Interesting, I wonder what went wrong before.

It looks like the p4a build is now working to the extent I'd expect, the 
original issue with orientation setting has been resolved.

The issue with sensor orientation crashing is new to me, I'm not sure if 
the cause is the swapinterval thing (quick googling suggests that may be 
benign) or something else. I'll try to look into it, but it may not be 
reproducible on my (older) device. Could you open a new github issue 
about this crash?

**Comment by Ham-Merhead** [comment]
OK will open new issue.

Two things I tried:
1) Build on different machine - problem reproduced
2) Comment out the Window.bind()  {or its contents} - problem removed 
    [but layout is not changed to account for rotation, so missing functionality]

**Comment by inclement** [comment]
> Comment out the Window.bind() {or its contents} - problem removed

Aha, this in combination with some of the errors makes me suspicious that the problem might be related to accessing Window attributes in the brief moments where the opengl context is replaced during reorientation. This would still be a bug, it is not intended and not something I've seen before, but it would give an idea of how to approach it.

If this is the case, you can probably work around it by binding Window.size to `Clock.schedule_once(the_resize_handler, 0.1)` instead of calling it directly. The 0.1 is a time in seconds, and possibly could be much lower, 0.1 is just large enough to assume the resize has been handled by now. It would be interesting to know if this works.

**Comment by Ham-Merhead** [comment]
Changed to ...
`        Window.bind(size=Clock.schedule_once(self._resize_handler, 0.1))`
and it worked, I did not see a crash.
So I have workaround (I think) - many thanks.
Changed the delay to 0.01 and saw crashes

Without this Clock.schedule(), I tried a window resize under Windows 10 (which is from the point of view of the app the same as a rotate) - no crash.

Still want me to open a new issue? Care to suggest a title?

**Comment by JonasT** [comment]
@inclement for what it's worth I followed some SDL2 issues regarding how the GL context cannot be accessed e.g. while the app is in background *at all* (well technically it appears to work at the first glance 95% of the time, but then textures corrupt and things break badly after a few times) so I wouldn't be surprised if a similar phase exists during rotate

**Comment by 1anre** [comment]
Please remove me from this thread.

**Comment by JonasT** [comment]
@1anre  that's not something a github maintainer can do, as far as I'm aware. you need to mute it yourself in your github notification settings. (e.g. see the "mute this thread" link)

**Comment by bavrock** [comment]
RESUME:
1) clean all (~/.android ~/.cache ~/.gradle etc)
2) p4a & kivy == master in .spec file
3) Window.bind(size=Clock.schedule_once(self._resize_handler, 0.1)) rotate no crash
