### ISSUE TITLE
seek() method on a file object doesn't use right arguments

### ISSUE THREAD

**Issue by goffi-contrib** [kivy/python-for-android#1768]
### Versions

* Python: 2.7.15
* OS: Android
* Kivy: N/A
* Cython: N/A

### Description

file objects' `seek` method doesn't use the right arguments. Normally when using `f.seek(0, os.SEEK_END)` (where f is an opened file), we put the position to the end of the file, and it works fine on standard GNU/Linux, but on Android it go the position `2` of the file (which is actually the value of `os.SEEK_END`). To actually go to the end of a file, one has to put `f.seek(os.SEEK_END)`, which is not the right signature (cf. https://docs.python.org/2.7/library/stdtypes.html#file.seek).

### reproduce

I build my app directly with P4A, but the following simple script should reproduce the issue:
```python
import sys, os
from tempfile import TemporaryFile


with TemporaryFile() as f:
    f.write(b'1234567890')
    f.seek(0, os.SEEK_END)
    size = f.tell()
if size != 10:
    print("TEST FAILED")
    sys.exit(1)
else:
    print("TEST SUCCEEDED")
    sys.exit(0)
```

Note that I haven't tested with Python 3, only Python 2.7.15

**Comment by goffi-contrib** [comment]
NOTE: after further testing, it seems that arguments are actually inverted (it seems to be `seek(whence, [offset])` instead of `seek(offset, [whence])`)

**Comment by JonasT** [comment]
For what it's worth @ all, it really appears to be broken for some reason. I tested this code:

```
import sys, os
from tempfile import TemporaryFile

print("start")
with TemporaryFile() as f:
    print("before: " + str(f.tell()))
    f.write(b'1234567890')
    f.seek(0, os.SEEK_END)
    print("after: " + str(f.tell()))
```
And if you build this with python-for-android with `--requirements=python2` it'll log the following output before instant-terminating (since obviously there is no proper UI to start):
```
start
before: 0
after: 2
Python for android ended.
```
And with the termux python 2 (patches are here I think https://github.com/termux/termux-packages/blob/master/packages/python2/configure.patch and none of them seem to fix anything in ftell) I get this:
```
$ python2 test.py
start
before: 0
after: 10
```
(which would be the expected output)

I am quite clueless why this happens though, neither termux nor our patchset seem to touch anything related. So I don't get why python would behave differently...

**Comment by JonasT** [comment]
Ok, I just did another test with python 3 and there **it works**. So this only affects python 2 apparently, and there mysteriously only our own python 2 version and not the one termux ships. (which at least regarding the I/O mdoules doesn't seem to have any significant difference in how it is patched to ours)

**Comment by Julian-O** [comment]
I am closing this as stale, because it only affected Python 2 and that is no longer supported, but I am nervous that the cause wasn't found, so if it continues to happen, please let us know.
