### ISSUE TITLE
Error in using debug flag, calling ANT debugger?

### ISSUE THREAD

**Issue by mittenchops** [kivy/python-for-android#179]
Running...

```
./build.py --package org.test.touchtracer --name touchtracer --version 1.0 --dir ~/mine/kivy/examples/demo/touchtracer/ debug
```

Gave me an error to ant.  Using Ubuntu 12.04:

```
Buildfile: /mine/python-for-android/dist/default/build.xml

BUILD FAILED
/home/mine/python-for-android/dist/default/build.xml:6: Source resource does not exist: /home/mine/python-for-android/dist/default/project.properties

Total time: 0 seconds
Traceback (most recent call last):
  File "./build.py", line 408, in <module>
    make_package(args)
  File "./build.py", line 332, in make_package
    subprocess.check_call([ANT, arg])
  File "/usr/lib/python2.7/subprocess.py", line 511, in check_call
    raise CalledProcessError(retcode, cmd)
subprocess.CalledProcessError: Command '['ant', 'debug']' returned non-zero exit status 1
machine@machine:~/mine/python-for-android/dist/default$ 
```

But works when I remove the debug at the end.

**Comment by alanjds** [comment]
Hi, @mittenchops.

I got the same problem. I have not SDK 8 installed, but in my environ is set ``ANDROIDAPI=14``. Still the ``build.py`` keeps targeting to 8. I guess [this line](https://github.com/kivy/python-for-android/blob/a43d8a5602f904a05dd57206bcee07f012a5fe79/src/build.py#L367) is ignoring the system environ.

Anyway, fixed by using ``./build.py --sdk 14 ... debug`` command link. The ``--minsdk`` one had not worked here.

Just confirm if it solves for you, ok? See ya.

**Comment by Kasramvd** [comment]
I got the same error but seems that the reason is because of  java : 

    Error: JAVA_HOME is not defined correctly.
  We cannot execute /usr/lib/jvm/jdk1.7.0/bin/java
Traceback (most recent call last):
  File "./build.py", line 508, in <module>
    make_package(args)
  File "./build.py", line 357, in make_package
    subprocess.check_call([ANT, arg])
  File "/usr/lib/python2.7/subprocess.py", line 540, in check_call
    raise CalledProcessError(retcode, cmd)
subprocess.CalledProcessError: Command '['ant', 'debug']' returned non-zero exit status 1

**Comment by Kasramvd** [comment]
@alanjds Do you mean this command : 

    ./build.py --package org.test.touchtracer --name touchtracer --version 1.0 --dir ./python-install/share/kivy-examples/demo/touchtracer debug

**Comment by alanjds** [comment]
Just to be sure: Do you have an SDK and NDK installed that can compile level 14?

**Comment by Kasramvd** [comment]
Yes I have the both bot I don't know that can compile level 14 or not! actually I think my main problem is because of that I have not the `ant` installed correctly, when I want to install it, It raised the following error : 

    download failed
   Oracle JDK 7 is NOT installed.

Since that I have JDK8 installed, am I need to install the JDK7?

**Comment by inclement** [comment]
I'm going to close this as a generic error. If you still have the issue, try building with the new toolchain and report the full error output.
