### ISSUE TITLE
ffmpeg recipe is broken on ndk19

### ISSUE THREAD

**Issue by misl6** [kivy/python-for-android#1996]
### Versions

* Python: 3.7.1
* OS: Ubuntu
* Kivy: master
* Cython: -

### Description

ffmpeg recipe that was building fine on `ndk 17c` now fails with `ndk 19b` (current `p4a==develop` recommended ndk)

The error is related to `gcc`. (starting from `ndk 18x` support to `gcc` was removed)
`ffmpeg` recipe should be updated to use clang.

**Comment by oukiar** [comment]
If helps to someone else, in ubuntu 19.04 for success compiling ffmpeg was necessary change the file buildozer.spec to use the python-for-android development branch.

`p4a.branch = develop`

The error was related to arm-linux-androideabi-gcc not detected, due to that buildozer project now forces to use the latest ndk 19b and as i can see the clang fixes for the ffmpeg recipe are only in the develop branch.

Regards.

**Comment by brentpicasso** [comment]
@oukiar  that helped me as well, thanks for the tip!

@AndreMiras when would we expect this to be moved to the stable branch?

**Comment by AndreMiras** [comment]
We don't have a planned release, ideally we should release often, but we don't :grimacing:

**Comment by hakanb78** [comment]
> If helps to someone else, in ubuntu 19.04 for success compiling ffmpeg was necessary change the file buildozer.spec to use the python-for-android development branch.
> 
> `p4a.branch = develop`
> 
> The error was related to arm-linux-androideabi-gcc not detected, due to that buildozer project now forces to use the latest ndk 19b and as i can see the clang fixes for the ffmpeg recipe are only in the develop branch.
> 
> Regards.

this literally saved my life. thank you so much!
