### ISSUE TITLE
Non-clear direction in readme guide

### ISSUE THREAD

**Issue by nicktime** [kivy/python-for-android#227]
Hi,

I'm new to Android and maybe I'm mistaken. But the guide in README.rst says get NDK r8c and latest platform which is 19 right now. But build fails with this combination. And judging by cdefs list it seems latest supported platform by this NDK is 14. 

build log http://pastie.org/9087824
cdefs list http://pastie.org/9087826

PS Sorry no Gist, I have some issues with it.

UPD Oh, sorry, I guess it was meant to be "Android SDK Platform-tools". It's just right now there's also list item named "SDK Platform" hence the confusion.

**Comment by FeralBytes** [comment]
So what is your suggestion to improve the documentation in the Readme? How can it be made more clear to you and for others in the future? Thanks for your input.

**Comment by Manmohana** [comment]
AFAIR it should have been instead of
"download latest Android platform, here API 14, which would be Android 4.0"
something like
"download "SDK platform" for Android 4.0 (API 14)"

I don't know if it is correct at this moment. But since the same NDK version is used - should be the same. I don't remember if it needs anything except SDK platform.

**Comment by FeralBytes** [comment]
OK, sounds good. 
Also I think the README.rst is messed up any ways since it has three # 1's...
It definitely should be re-written for clarity.

**Comment by inclement** [comment]
This should not be an issue in the new doc (it has other issues, just not this one!). Thanks.
