### ISSUE TITLE
*.so is too small to be an ELF executable

### ISSUE THREAD

**Issue by trivedigaurav** [kivy/python-for-android#234]
Running a packaged kivy app on Android causes: "ImportError: dlopen failed: "/data/data/org.test.sms/files/lib/python2.7/site-packages/kivy/properties.so" is too small to be an ELF executable.

Run Log (using logcat): https://gist.github.com/trivedigaurav/74197a06807c4abdb485
Build Log (using P4A): https://gist.github.com/trivedigaurav/8203502e17bd1cf52e31

*Related:*
* Groups Discussion: https://groups.google.com/d/topic/kivy-users/jvnpObU-Ukc/discussion
* (Possibly) Related Bug: https://github.com/kivy/python-for-android/issues/77

**Comment by thegrymek** [comment]
Hi, 

I have the same error when I set P4A_pyjinius_DIR.

**Comment by cbenhagen** [comment]
I am running into the same error with NO P4A_pyjinius_DIR set. https://github.com/kivy/python-for-android/pull/251 did not fix it.

**Comment by cbenhagen** [comment]
I finally found what triggered this error in my case: pyyaml. Actually the pyyaml recipe. After removing it from p4a (`rm -f .buildozer/android/platform/python-for-android/recipes/pyyaml`) my app worked again. While this is only a workaround it might help narrow down the actual bug. Or at least it would help someone who got bitten by it.

I tested on Ubuntu 14.04 and OSX 10.10.2 with a minimal hello world example: https://gist.github.com/cbenhagen/e16da236c3aa821d0a81

**Comment by dl1ksv** [comment]
I get the same problem when building ( and running ) the compass example of kivy from a fresh git checkout
distribute.sh -m "kivy"
The only adaptation I  made was setting the toolchain version to 4.6 instead of 4.4.3 in distribute.sh
The file jnius.so is empty ( 0 byte).
Looking into the build messages I got

creating build/lib.linux-x86_64-2.7/jnius
/home/schroer/python-for-android/src/tools/liblink -lm -L/home/schroer/python-for-android/build/libs -DANDROID -mandroid -fomit-frame-pointer --sysroot /opt/android-ndk/platforms/android-14/arch-arm build/temp.linux-x86_64-2.7/jnius/jnius.o -Llibs/armeabi -L/home/schroer/python-for-android/build/python-install/lib -lsdl -llog -lpython2.7 -o build/lib.linux-x86_64-2.7/jnius/jnius.so
/home/schroer/python-for-android/build/python-install/lib/python2.7/distutils/dist.py:267: UserWarning: Unknown distribution option: 'install_requires'
  warnings.warn(msg)
running install

To avoid The UserWarning I patched pyjnius/setup.py by

--- pyjnius/master/setup.orig.py	2015-06-27 17:53:45.939286150 +0200
+++ pyjnius/master/setup.py	2015-06-27 17:54:21.783483210 +0200
@@ -1,4 +1,7 @@
-from distutils.core import setup, Extension
+try:
+    from setuptools import setup, Extension
+except ImportError:
+    from distutils.core import setup, Extension
 from os import environ
 from os.path import dirname, join, exists
 import sys

and run 

distribute.sh -m "setuptools kivy"

Now I get the build error 
creating build/lib.linux-x86_64-2.7/jnius
/home/schroer/python-for-android/src/tools/liblink -lm -L/home/schroer/python-for-android/build/libs -DANDROID -mandroid -fomit-frame-pointer --sysroot /opt/android-ndk/platforms/android-14/arch-arm build/temp.linux-x86_64-2.7/jnius/jnius.o -Llibs/armeabi -L/home/schroer/python-for-android/build/python-install/lib -lsdl -llog -lpython2.7 -o build/lib.linux-x86_64-2.7/jnius/jnius.so
running install
Traceback (most recent call last):
  File "setup.py", line 142, in <module>
    'Topic :: Software Development :: Libraries :: Application Frameworks'])
  File "/home/schroer/python-for-android/build/python-install/lib/python2.7/distutils/core.py", line 152, in setup
    dist.run_commands()
  File "/home/schroer/python-for-android/build/python-install/lib/python2.7/distutils/dist.py", line 953, in run_commands
    self.run_command(cmd)
  File "/home/schroer/python-for-android/build/python-install/lib/python2.7/distutils/dist.py", line 972, in run_command
    cmd_obj.run()
  File "/home/schroer/python-for-android/build/python-install/lib/python2.7/site-packages/setuptools/command/install.py", line 76, in run
    self.do_egg_install()
  File "/home/schroer/python-for-android/build/python-install/lib/python2.7/site-packages/setuptools/command/install.py", line 85, in do_egg_install
    easy_install = self.distribution.get_command_class('easy_install')
  File "/home/schroer/python-for-android/build/python-install/lib/python2.7/site-packages/setuptools/dist.py", line 395, in get_command_class
    self.cmdclass[command] = cmdclass = ep.load()
  File "/home/schroer/python-for-android/build/python-install/lib/python2.7/site-packages/pkg_resources.py", line 1954, in load
    entry = __import__(self.module_name, globals(),globals(), ['__name__'])
  File "/home/schroer/python-for-android/build/python-install/lib/python2.7/site-packages/setuptools/command/easy_install.py", line 12, in <module>
    import sys, os.path, zipimport, shutil, tempfile, zipfile, re, stat, random
  File "/home/schroer/python-for-android/build/python-install/lib/python2.7/zipfile.py", line 6, in <module>
    import io
  File "/home/schroer/python-for-android/build/python-install/lib/python2.7/io.py", line 60, in <module>
    import _io
ImportError: /home/schroer/python-for-android/build/python-install/lib/python2.7/lib-dynload/_io.so: wrong ELF class: ELFCLASS32

I tested on gentoo with these settings

Check environment
SDK located at /opt/android-sdk-update-manager/
NDK located at /opt/android-ndk
NDK version is r8c
API level set to 14

**Comment by akshayaurora** [comment]
@dl1ksv yours is a different error than the original one in this issue the original issue happens on device when the build is not recompiled which should not happen anymore cause we force recompilation.

Your issue which is raised while compiling is most probably cause of issues with python installation being broken, @ecdsa found out that this was the cause of a similar error as yours. He solved the issue with installing python using `apt-get`.
