### ISSUE TITLE
Problem with ffmpeg on Android

### ISSUE THREAD

**Issue by HugoAch** [kivy/python-for-android#2345]
I have developed an application that requires the `ffmpeg` module, but when I export the Android APK with buildozer [ffmpeg as a requirement] the module is not available. The app throws `[Errno 13] Permission denied: ffmpeg`.

Any suggestions?

**Comment by RobertFlatt** [comment]
It sounds like Android is refusing to let the app execute a stand alone executable - this is the expected behavior of Android.

The recipe builds .so files, not an executable, see https://github.com/kivy/python-for-android/blob/develop/pythonforandroid/recipes/ffmpeg/__init__.py line 84

Does the app try to execute a ffmpeg binary with exec() or something similar?  Android does not allow that (and it is not in the build)

Usage questions are best directed to the user group https://groups.google.com/g/kivy-users

**Comment by HugoAch** [comment]
Thank you for your response, you mentioned the key point: I needed to call the .so file, not an executable (I am not and experimented Android developer). Now, I have two different cases on ffmpeg calls in my Kivy app: desktop and android.

But nevertheless, the ffmpeg.so library is not built on buildozer, I had to call the silentlexx `libffmpeg.so` (previously I installed his app https://github.com/silentlexx/android_ffmpeg_buildtool)

**Comment by RobertFlatt** [comment]
> Kivy app: desktop and android.

Yes because the desktop is POSIX compliant and Android is not.

> the ffmpeg.so library is not built on buildozer,

I see what you are saying but it exceeds my understanding.

**Comment by oukiar** [comment]
maybe you can use ffpyplayer, depends on your needs

**Comment by purushottam858** [comment]
Did you figure it out , how to run ffmpeg in kivy Android app ?

**Comment by Julian-O** [comment]
Closing as no response
