### ISSUE TITLE
Kivy app crashing on android after installation, what is the issue here?

### ISSUE THREAD

**Issue by rizwan-amir** [kivy/python-for-android#2433]
python  :  Traceback (most recent call last):
02-28 18:44:49.164 17248 17312 I python  :    File "/content/.buildozer/android/app/main.py", line 16, in <module>
02-28 18:44:49.165 17248 17312 I python  :    File "/content/.buildozer/android/platform/build-armeabi-v7a/build/python-installs/maidenapp/cv2/__init__.py", line 5, in <module>
02-28 18:44:49.166 17248 17312 I python  :  ImportError: dlopen failed: "/data/data/maiden.test.maidenapp/files/app/_python_bundle/site-packages/cv2/cv2.so" is 64-bit instead of 32-bit
02-28 18:44:49.166 17248 17312 I python  : Python for android ended.

**Comment by RobertFlatt** [comment]
We know that opencv works, so this looks like pilot error. But I suspect not....

1) There is a history of unresolved cases like this https://groups.google.com/g/kivy-users/search?q=cv2.so

2) Typing to the OP on Reddit, they are using an arm7 device  https://www.reddit.com/r/kivy/comments/lvfutk/my_android_app_made_in_kivy_crashes_on_being/

3) Looking at the recipe we see that the build instructions for cv2.so are different
Its build arch depends not on arch.arch but on the Python build architecture.
https://github.com/kivy/python-for-android/blob/develop/pythonforandroid/recipes/opencv/patches/p4a_build.patch#L2

So I suspect the recipe is always building a 64-bit cv2.so , which is exactly the message the OP gets.
This was not found previously because an arm7 (or mixed binary) will run on arm8, and an arm7 binary will run on arm7, it just the mixed binary generated by this recipe that won't run on an arm7 device.

**Comment by RobertFlatt** [comment]
My guess I was wrong 
```
cd .buildozer/android/platform/build-armeabi-v7a/dists/myapp__armeabi-v7a/_python_bundle/_python_bundle/site-packages/

file cv2.so
cv2.so: ELF 32-bit LSB shared object, ARM, EABI5 version 1 (SYSV), dynamically linked, BuildID[sha1]=904e27df6a9748088bfb80ed7c04030c6123d16f, stripped

```

**Comment by lowdelas** [comment]
Follow [this](https://www.youtube.com/watch?v=c4tuSxSoERY) tutorial. It worked for me.
