### ISSUE TITLE
Feature request for upcoming fushia OS

### ISSUE THREAD

**Issue by syleishere** [kivy/python-for-android#2442]
Build an interpreter for python along with all popular modules into flutter/dart. Can currently link .so file into it with ffi, but no real python implementation. As google has stated Python will not be accepted into fushia, it would be great to link it in.

**Comment by tshirtman** [comment]
As far as i know fushia is not android, so i don’t think this project is the proper place to discuss that, if you want to start a fushia port of python and that taking from p4a is useful, feel free to do it, considering fushia has been mostly staying under the radar since announced in 2016, i would not put any significant effort into supporting it yet, if phones start to get released with it, that could be a different question, but that could still be years in the future, and it’s very hard to tell if that would get any significant user adoption, as, as history shows, even tech giants like microsoft or samsung can fail to make a dent in the marked with a mobile OS.
