### ISSUE TITLE
Start a background sticky service that auto-restart.

### ISSUE THREAD

**Issue by Pycode80** [kivy/python-for-android#2767]
### Versions

- Python:3.9
- OS:Debian 11
- Kivy:2.1.0

### Description

I want to start a service in the background when the user clicks on a button. I use python and KIVY and my application is for Android devices. My problem is that I want the service I run in the background to restart automatically when the phone reboots. I saw in the p4a documentation that I should put :sticky:foreground in the buildozer spec and add the permission. I've seen in the p4a documentation that you have to put :sticky:foreground in the buildozer spec and add the permission, but my service starts when I click on the button but when I restart my smartphone. It doesn't launch anymore (I don't have the notification that informs me of its presence).

### buildozer.spec

```sh
:sticky:foreground
android.permission.FOREGROUND
```

**Comment by Pycode80** [comment]
Answer here : https://github.com/kivy/kivy/wiki/Starting-Kivy-App-and-Service-on-bootup-on-Android

**Comment by vishakraj25** [comment]
@Pycode80 , I tried this solution, but it is not working, this link - https://github.com/kivy/kivy/wiki/Starting-Kivy-App-and-Service-on-bootup-on-Android has the good explanation, but there are few things has to be clarified to understand well,

in the java code, could you please explain the `ix.putExtra` statements

1. what is the difference between `package_root` and `app_root`,
2. should the `serviceEntrypoint` has to assign for the service python file?
3. what is the `pythonName` 
4. what is the `pythonServiceArgument`

i searched but didnt get the documentation, because the path and the app package name will be differ from the project, so, if we clarify the above mentioned statements, it would be easier to work on

thanks

**Comment by Julian-O** [comment]
This is a support question. Please take it to the support channels.

**Comment by vishakraj25** [comment]
How to take this email to support channel, please let me know

Thanks

**Comment by Julian-O** [comment]
Visit the README file on the front page of https://github.com/kivy/kivy, and search for "support".
