### ISSUE TITLE
opening files in other apps 

### ISSUE THREAD

**Issue by USER4247** [kivy/python-for-android#2906]
I have made a code in jnius to open pdf files in other apps , but I cant open files . Here is code
`def test_pdf(self):

        PythonActivity = autoclass('org.kivy.android.PythonActivity')

        Intent = autoclass('android.content.Intent')

        Uri = autoclass('android.net.Uri')

        intent = Intent()

        intent.setAction(Intent.ACTION_VIEW)

        url1 = "storage/emulated/0/classified_oct23/yourfile.pdf"

        pdf = "dummy.pdf"

        uri = Uri.parse(url1)

        intent.setDataAndType(uri, 'application/pdf')  # Adjust the MIME type as needed

        current_activity = PythonActivity.mActivity

        current_activity.startActivity(intent)`

**Comment by RobertFlatt** [comment]
Usage issues should be directed to the user groups.

Also read about Android storage https://github.com/Android-for-Python/Android-for-Python-Users#android-storage, particularly the Android version is important. I don't think the code would work on Android >= 10. Also since you (apparently) want to read from another app's shared storage consider permissions.

For any follow up use the User Groups.

**Comment by USER4247** [comment]
> Usage issues should be directed to the user groups.
> 
> Also read about Android storage https://github.com/Android-for-Python/Android-for-Python-Users#android-storage, particularly the Android version is important. I don't think the code would work on Android >= 10. Also since you (apparently) want to read from another app's shared storage consider permissions.
> 
> For any follow up use the User Groups.

I found the solution , I used WebBrowser to open any file instead , but To do so , One must pass Content flag to uri so it can be accessed
