### ISSUE TITLE
About ctypes

### ISSUE THREAD

**Issue by Hans2011** [kivy/python-for-android#319]
The _ctypes.so of python 2.6.2 works well on my app(android/arm), i want to use PIL so i decide
to upgrade to Python 2.7.x, 

But _ctypes was disable on Python 2.7.2(Py4A)
 As the guide on bitbucket, modify 3 files, distribute.sh disable-moduels.patch and recipe.sh. but I failed, the _ctypes.so not present after python compiled.

As an older issue on github i cp the lib.linux-i686-2.7/_ctypes.so to python-install/.../lib-dynload/, 
and i got a error:
from _types import Union, Structure, Array
 "could not load needed library 'libphread.so.0' for '_ctypes.so'

Anybody can help me or send me a complete python-install package( 2.7.2).
Thank you very much!

**Comment by aoncorici** [comment]
Take a look at this: https://github.com/kivy/python-for-android/issues/301
I can help with python2.7.x package, what is exactly that you want from build or dist folder?

**Comment by olymk2** [comment]
any chance we will see this working, i have been trying myself to get it to work but i am kind of stabbing around in the dark.

seems this stops you using ctypes but also effects multiple python libraries that use it under the hood, in my case i can not import freetype because _ctypes.so is unavailable.

It seems there is a fix around so could that not be merged ?

**Comment by tito** [comment]
Ctypes is now part of Python for android!
