### ISSUE TITLE
Python 2.7.2 don't build cleanly with GCC ≥ 4.8

### ISSUE THREAD

**Issue by rdoursenaud** [kivy/python-for-android#321]
Due to http://bugs.python.org/issue17547, python (and hostpython) targets don't build cleanly with GCC ≥ 4.8.

This makes buildozer useless here on my Arch Linux.

Is there any plan to update Python or should I backport the patch ?
##

**Comment by FeralBytes** [comment]
Is this a p4a issue or is it really a Python issue, I see the issue you linked and it is mark resolved. So what really is the issue? Sounds to me like an Arch issue as you are waiting for Arch to push the patched versions of Python, is that right?
Also the issue that you reference against buildozer #153 does not seem related to me, because it is a Java Exception that kevinkjt2000 is experiencing, but the python issue from above is a GCC compiler flag error.
I am really just trying to understand better so, please expand as able, thank you.

**Comment by rdoursenaud** [comment]
This is a python-gcc compatibility issue that's bleeding into p4a because of the outdated python version used. It's fixed upstream but not in the version used by p4a.
The buildozer bug may not be related but its p4a build log clearly show the same symptoms I have.

**Comment by inclement** [comment]
No longer an issue with the build tools moving to clang.
