### ISSUE TITLE
Failed Cython Compilation

### ISSUE THREAD

**Issue by jayece09** [kivy/python-for-android#325]
When I ran ./distribute.sh -m "openssl pil kivy" for making packaging for Android it failed with:-

***********************************************
building 'kivy.graphics.vertex_instructions' extension
************/temp.linux-x86_64-2.7/kivy/graphics/vertex_instructions.o
kivy/graphics/vertex_instructions.c:1:2: error: #error Do not use this file, it is the result of a failed Cython compilation.
 #error Do not use this file, it is the result of a failed Cython compilation.
  ^
 error: command 'ccache' failed with exit status 1

*************************************************************************
Exactly similar errors were found while building using buildozer.
Even at instances I had Cython the buildozer method returned  Cython not found!

What's should be probable remedial steps?

**Comment by FeralBytes** [comment]
Can you try the fix referenced [here](https://github.com/kivy/python-for-android/issues/306#issuecomment-68661031). But also note that on Linux Mint I am using the latest version of Cython installed via pip without issue; so ultimately I recommend you update Cython.
If this works for you please post back so that both issues can be closed.

**Comment by gunsmoker70** [comment]
I had the same issue with the latest cython (0.22). Switching to 0.20.1 solved the problem.
