### ISSUE TITLE
TextInput error

### ISSUE THREAD

**Issue by mstetter** [kivy/python-for-android#357]
It seems that there is an error in the TextInput. When deleting a character which has just been typed into the TextInput then the remaining characters are added.
for example when deleting the 't' in 'test' it makes 'testtes'.
##

**Comment by tito** [comment]
Ping @akshayaurora

**Comment by inclement** [comment]
Anyone know if this is still active? I know @akshayaurora fixed several such issues.

**Comment by CodeLexis** [comment]
The error is still occurring. I've asked this same question severally on Kivy Groups (the Google Group), still awaiting replies on all of them.

**Comment by KeyWeeUsr** [comment]
@CodeLexis try to check [this issue](https://github.com/kivy/kivy/issues/4173) and the linked issues in it. I believe it's the old Android bug. I'm not sure if it's fixed on newer devices, but I could reproduce it with my `4.4.2` Samsung Galaxy Note 2

**Comment by Zen-CODE** [comment]
Yes. This is old adroid bug.

https://github.com/kivy/kivy/issues/3284
https://github.com/kivy/kivy/issues/1773

Issue regarding copying of words/text is a Android OS issue, and happens with non Kivy applications like email clients. This can be fixed by:

    Unticking "Next Word Prediction".
OR
    Switching off word completion.

Both cannot be switched on.
What happens is it goes back in your word prediction as you press space, it then enters that prediction automatically in random order or it just duplicates your text and mixes it with predictions.
Here is links to the same issue (Not kivy related)

​http://forum.swype.com/showthread.php?12403-Duplicating-words-after-pressing-space-amp-backspace
​https://www.phonearena.com/news/SwiftKey-glitch-causes-double-trouble-for-Android-users-after-update-UPDATE_id70887
