### ISSUE TITLE
[revamp] The revamp branch always prints the ToolchainCL object after running

### ISSUE THREAD

**Issue by inclement** [kivy/python-for-android#452]
As per the title, the revamp branch always prints the ToolchainCL object after running. For instance, the output of `p4a clean_all` is:

    [INFO]:    This python-for-android revamp is an experimental alpha release!
    [INFO]:    It should work (mostly), but you may experience missing features or bugs.
    <pythonforandroid.toolchain.ToolchainCL object at 0x7f9e4f461e50>

I'm opening an issue here because I have no idea why. Maybe it can be a simple issue for someone to fix.

**Comment by str4d** [comment]
The reason is that you have the `console_scripts` entry point pointing at a class, rather than a function. `setuptools` generates a shim for each entry point that calls its corresponding function and then passes the returned value to `sys.exit()`. Because the entry point is a class, `sys.exit()` is passed the value returned by `ToolchainCL()`, which is the `ToolchainCL` object. `sys.exit()` then takes the non-`None` value [as an error message and prints it](https://docs.python.org/2/library/sys.html#sys.exit).

[The fix](http://www.scotttorborg.com/python-packaging/command-line-scripts.html) is to move most of `ToolchainCL.__init__()` to some `main()` function, and set that as the `console_scripts` entry point.

**Comment by inclement** [comment]
Thanks a lot, I've fixed it now. That's been annoying me for ages!
