### ISSUE TITLE
SDL2 backend doesn't support a loading screen

### ISSUE THREAD

**Issue by inclement** [kivy/python-for-android#465]
The SDL2 backend doesn't support an icon splash screen like the pygame one.

This should be quite easy to add and might be an easy first contribution.

I'd like this to be more configurable than the old pygame one, particularly giving an option for a different image on the first run. SDL2 loads faster than pygame so some apps may be better off having no splash screen on later runs, as it actually makes things feel slower.

**Comment by tito** [comment]
Things tried:

1. Making a new theme and manually set a android:windowBackground (as per https://forums.libsdl.org/viewtopic.php?p=42213&sid=b47fa9922cfda52a79444393cc7ad9c4#42213). This works during the extract, but then goes black. This is due to the order: first we unpack the data, then initialize super()//SDL. The SDL set a new content view, create the gl context, and everything goes black.

2. I tried the previous approach by displaying a GL texture on the screen until the app is ready. This doesn't work yet, as many part of the GL initialisation are hidden into SDL itself. Which mean we can't fully implement it in Java.

Concerning 2., the idea was to reverse the order: first create SDL context, then unpack and start the app. This require few changes to the SDL activity in order to make it right. Nevertheless, SDL (unlike its SDL iOS port) doesn't seem to have a proper way to achieve loading screen.

I'll try a third way, which is to add another widget in top of the SDL surface, containing the bitmap.
