### ISSUE TITLE
python multiprocess.dummy do not work

### ISSUE THREAD

**Issue by Tungsteno74** [kivy/python-for-android#479]
Hello, I tried to import the class multiprocess.dummy in QPython but I get the following error:
>File "/QPython/QPython2-core/build/python-install/lib/python2.7/multiprocessing/__init__.py", line 84, in <module>
>ImportError: No module named _multiprocessing

So before i use this module in a multiplatform application (that will use python-for-Android for mobile devices) I wanted to know if it works with this framework.
If it does not work, is possible to see its implementation in the short?

I think that it would be very useful since this module is the only way to bypass the GIL in Python applications and optimize desktop programs. Whereas, for the moment, on mobile devices is not possible to implement multiprocessing, it would be useful to have a surrogate to do this.

Sorry for my bad english.
thanks for your help

**Comment by inclement** [comment]
multiprocessing.dummy is stripped by python-for-android by being listed in https://github.com/kivy/python-for-android/blob/master/pythonforandroid/bootstraps/pygame/build/blacklist.txt (this is in a different place in the old toolchain but is still called blacklist.txt). This is deliberate, but i don't know if the reason is that it doesn't work or that it's just taken out to save space.

Either way, you can try including it by whitelisting that file/folder with the whitelist option of python-for-android.

**Comment by Tungsteno74** [comment]
@inclement 
I'm not able to find a guide on how to use the whitelist.
Please, can you tell me step-by-step how to add *multiprocess.dummy* to *QPython* whitelist?
So I can see if it works.
thanks

**Comment by inclement** [comment]
With qpython I have no idea, it's probably impractical - presumably
you'd instead need to build qpython itself with the module included.
