### ISSUE TITLE
CythonRecipe: how to handle different settings for different .pyx files?

### ISSUE THREAD

**Issue by hottwaj** [kivy/python-for-android#511]
Hey there, I have an issue that I'm not sure how to make progress on...

The CythonRecipe framework in the revamp framework seems to use the same settings (includes, libs, etc) for every .pyx file in a recipe.  

Unless I'm missing something (quite possible!) this is a problem for a custom library I've built because:
1. the library has some .pyx files that use c and others that use c++, and I can't give instructions on which files to compile using c++ settings (c is assumed for all by the CythonRecipe)
2. the library has a couple of .pyx files that import different external libs, and I can't specify which .pyx file imports which lib

When using the old toolchain issues 1 and 2 were delegated to the setup.py file I wrote for my library, but with the revamp my setup.py is not actually used to cythonise the .pyx, hence 1 and 2 cause problems.

Am I missing something, or any ideas on how to make progress?  Can I somehow use my setup.py to cythonise my .pyx files, instead of relying on the CythonRecipe?

Thanks!

**Comment by inclement** [comment]
I thought the revamp does the same as the old toolchain here - for instance, the [Kivy recipe](https://github.com/kivy/python-for-android/blob/old_toolchain/recipes/kivy/recipe.sh#L30) shows how the files are cythonised outside the setup.py. The CythonRecipe is supposed to just abstract this to a single class, where [this part](https://github.com/kivy/python-for-android/blob/master/pythonforandroid/toolchain.py#L2215) duplicates exactly what the recipe.sh did. I don't think it was ever generally possible to let the setup.py do the cythonising because cython wasn't installed in the hostpython.

I guess I'm missing something here though, am I wrong about it, or is there a recipe in the old toolchain that demonstrates what you're trying?

I'm not sure how to solve your issue, but certainly it should be a reasonable thing to do. Maybe it would help if you could show your old recipe.sh, would that be possible?

**Comment by hottwaj** [comment]
Well that's embarassing: as soon as I read your reply I remembered that I had had to write a customised recipe for the old toolchain, but I'd forgotten that I had done that and assumed it was all in the setup.py file...  Sorry for wasting time and thanks for pointing me in the right direction!

**Comment by inclement** [comment]
No worries. It sounds like your customisation is more advanced than the
current CythonRecipe, if you think it can be generalised then feel free
to suggest an upgrade to the CythonRecipe, or an alternative with your
method.
