### ISSUE TITLE
Kivy Launcher 1.9.1 APK doesn't work on Lollipop

### ISSUE THREAD

**Issue by zennobjects** [kivy/python-for-android#548]
I think the Kivy Launcher 1.9.1 is broken. Uninstalling 1.9.1 and then installing the 1.90 APK or 1.8.0 permits me to run my apps again within the /sdcard/kivy folder.  But when I uninstall 1.9.0 or 1.8.0 and re-install 1.9.1, that process doesn't solve the problem for me.  Kivy Launcher 1.9.1 doesn't run.

The Kivy Launcher 1.9.1 app appears to hang (nothing changes on the screen for a few seconds) and then the Launcher screen blanks under the Launcher title action bar and the app crashes.

I've tried deleting the /sdcard/kivy/myappfolder/.kivy - the hidden folder within any of my application folders in case there are traces of 1.9.0 that are preventing 1.9.1 from launching but that doesn't work. Maybe the 1.9.1 Launcher has a problem on Note 4's with Lollipop? 

I arrived at this situation because Google Play and Google's Lollipop automatically upgrades in the background (without asking the user) APKs that don't have permission beyond the norm.  So I awoke to a new 1.9.1 Kivy Launcher sitting within my Note 4  that wouldn't run.

**Comment by xiaogigagagigigo** [comment]
yes, same problems here: automatic update seems to be enabled on my Sony Z4/Lollipop and now I have Kivy Launcher 1.9.1 with exactly the symptoms you described. It has driven me crazy for 2 days now - thanks for your post, since I was searching in my own kivy code all the time - aaaaa ...

I think there is (also?) a problem with the .kivy-folder (or before?) as during the install of a new kivy-app the app exits before generating that folder. 

Did you find a solution? 
Did you manage to disable automatic updates in lollipop?

**Comment by zennobjects** [comment]
I haven't  found a fix for the Kivy Launcher but I did find a way to turn off automatic update for this app only.
Go to the Googlr Play Store app on your phone and open it (start her up). Click on the menu button icon at the top left corner of the screen.
Scrpll down to 'settings'.
Make sure either of the two automatic update options is selected.  Obviously one of them has to be already selected.  Otherwise we wouldn't be having this conversation. 
Then back out to the main screen and open the menu choices again. (either by swping the screen from left to right or by clicking on the menu item at the top left.
Choose 'my apps and games'.   Then scroll through your list of installed apps until you find that demon possessed program called Kivy Launcher.  Click on it and when the overview screen appears, hit the tiny icon at the top right corner.  There will be only one option showing called 'auto update' deselect it and you're good to go.


Sent from my Samsung device

-------- Original message --------

**Comment by inclement** [comment]
Do any of you have an adb logcat log of the result when trying the new (broken) launcher version?

**Comment by xiaogigagagigigo** [comment]
I would like to do so, but sorry - as I'm a noob here - I don't know how. I installed a terminal app and gave it a 
  $ adb logcat > /sdcard/logcat.txt
now it shows " - waiting for device - "
I started Kivy Launcher + pong (in portrait-mode) reproducing the described situation.
There exists a file  /sdcard/logcat.txt, but it's still empty.
How should I continue?

**Comment by xiaogigagagigigo** [comment]
For now I can provide this: If I start pong in landscape-mode it's running and generates the .kivy-folder plus logs. And maybe the starting of the log already helps, it shows this ...
[INFO              ] Logger: Record log in /storage/emulated/0/kivy/pong/.kivy/logs/kivy_16-02-14_0.txt
[WARNING           ] [Config      ] Upgrading configuration in progress.
[WARNING           ] [Config      ] Older configuration version detected (0 instead of 14)
[ERROR             ] Error when copying logo directory
[INFO              ] Kivy: v1.9.1
[INFO              ] Python: v2.7.2 (default, Jan  4 2016, 01:54:59)

**Comment by xiaogigagagigigo** [comment]
Ah - no, forget my last comment, as I looked into older logs and they show similar messages like ...
[INFO              ] Logger: Record log in /storage/emulated/0/kivy/pictures/.kivy/logs/kivy_15-10-12_0.txt
[WARNING           ] [Config      ] Upgrading configuration in progress.
[WARNING           ] [Config      ] Older configuration version detected (0 instead of 13)
[ERROR             ] Error when copying logo directory
[INFO              ] Kivy: v1.9.0
[INFO              ] Python: v2.7.2 (default, Apr  2 2015, 13:52:41) 
... so we get actually no new info for this problem here.

By the way, meanwhile I rebooted my android, hoping that /sdcard/logcat.txt would be filled up and closed, but it's still empty :-(

**Comment by zennobjects** [comment]
I uploaded the full 2.7 MB file to  pastefile only to discover that it 
will take one week before it's viewable.
Here are two snippits near  the end of the adb logcat log that I 
captured.  The python extraction seems to proceed smoothly up to this 
point, which is where the last python entries occur;

I/python  (12422): extracting lib/python2.7/lib-dynload/syslog.so
I/python  (12422): extracting lib/python2.7/lib-dynload/_hashlib.so
W/ResourceType(12422): No package identifier when getting value for 
resource number 0x00000000
D/CustomFrequencyManagerService(16621): releaseDVFSLockLocked : Getting 
Lock type frm List : DVFS_MIN_LIMIT  frequency : 1958400 uid : 1000  pid 
: 16621  tag : ACTIVITY_RESUME_BOOSTER@9
E/art     (12422): 
dlopen("/data/data/org.kivy.pygame/files/lib/python2.7/lib-dynload/_imaging.so", 
RTLD_LAZY) failed: dlopen failed: library 
"/data/data/org.kivy.pygame/files/lib/python2.7/lib-dynload/_imaging.so" 
not found
I/python  (12422): Starting audio thread
W/ActivityManager(16621): mDVFSHelper.release()

......

Then there are a couple of kivy related entries further along;


\\I/AndroidRuntime(12422): VM exiting with result code 0, cleanup skipped.
W/InputDispatcher(16621): channel ~ Consumer closed input channel or an 
error occurred.  events=0x9
E/InputDispatcher(16621): channel ~ Channel is unrecoverably broken and 
will be disposed!
W/InputDispatcher(16621): Attempted to unregister already unregistered 
input channel
I/WindowState(16621): WIN DEATH: Window{1be26066 u0 d0 
org.kivy.pygame/org.renpy.android.PythonActivity}
I/ActivityManager(16621): Process org.kivy.pygame:python (pid 12422)(adj 
0) has died(132,597)
D/ActivityManager(16621): isAutoRunBlockedApp:: org.kivy.pygame, Auto Run ON
W/ActivityManager(16621): Force removing ActivityRecord{3ebb5363 u0 
org.kivy.pygame/org.renpy.android.PythonActivity t20338}: app died, no 
saved state
V/ApplicationPolicy(16621): isApplicationStateBlocked userId 0 pkgname 
org.kivy.pygame
V/ApplicationPolicy(16621): isApplicationStateBlocked userId 0 pkgname 
com.android.vending
D/InputDispatcher(16621): Focused application set to: xxxx
I/SurfaceFlinger(  313): id=15810 Removed qygame (4/8)
I/SurfaceFlinger(  313): id=15810 Removed qygame (-2/8)


Then nothing more is seen or heard of from python or kivy.

binpaste url
http://binpaste-rascalking.rhcloud.com/pastes/144

pastefile (not yet showing, I just put this here as a reminder to self 
to check it one week from now)
http://www.pastefile.com/myfiles

Regards,
Steph

**Comment by zennobjects** [comment]
Ooops, the url has nothing in it.  Please use this one

[Kivy Launcher 1.9.1 Broken adb logcat ](http://pastebin.com/7w8QgPgH)

**Comment by xiaogigagagigigo** [comment]
I think this  - [https://github.com/kivy/kivy/issues/3937](https://github.com/kivy/kivy/issues/3937) - is related to our problem, if not identical. For me I can commit it's depending on orientation-setting in android.txt.

**Comment by akshayaurora** [comment]
New Launcher in market has been uploaded by @tito
