### ISSUE TITLE
Multiple permissions in .p4a

### ISSUE THREAD

**Issue by brussee** [kivy/python-for-android#673]
If I use --permission CAMERA,INTERNET just like with --requirements for recipes I get this error:

```
     [aapt] /home/paul/.local/share/python-for-android/dists/testproject/bin/AndroidManifest.xml:31: Tag <uses-permission> attribute name has invalid character ','.    

BUILD FAILED    
/home/paul/android-sdk-linux/tools/ant/build.xml:649: The following error occurred while executing this line:   
/home/paul/android-sdk-linux/tools/ant/build.xml:694: null returned: 1
```

This does work: --permission CAMERA --permission INTERNET but gets annoying for all the permissions I want.
##

**Comment by inclement** [comment]
I see no major reason not to allow this (or maybe a --permissions), if someone would like to make a PR it should be fine.

**Comment by KeyWeeUsr** [comment]
This could be probably closed after [bdist](https://github.com/kivy/python-for-android/blob/master/pythonforandroid/bdistapk.py) is documented, as there is an option for multiple permissions in bdist since #898 _and_ it makes a usage of p4a much more comportable:

    python <file> apk

rather than:

    p4a --to --infinity --and_beyond

😋 

with a file constructed like [this](https://github.com/kivy/python-for-android/blob/2004698e8b34a67c05a113626a9708ead182a97a/testapps/testlauncher_setup/sdl2.py) + after #965 you could just import the permission groups and put them into the dictionary like this:

    from pythonforandroid import permissions as p
    options = {'apk': {.......
                   'permissions': p.SENSORS + p.NETWORK}}

**Comment by inclement** [comment]
I'd like to make toolchain.py accept --permissions as well as just the bdist command.
