### ISSUE TITLE
Back button doesn't work

### ISSUE THREAD

**Issue by Tungsteno74** [kivy/python-for-android#699]
For some reason the back button doesn't work with sdl2, but work well with pygame backend (the app is closed) . When pressing, the button light up and vibrate but nothing else happens. 
It could be a problem for event interception by the engine? 

OS: Android 4.4.2

Some confirmation?

**Comment by kived** [comment]
Yes, in the pygame backend we have mapped the Android Back button to 27 (ESC), but have not done so yet for SDL2.

**Comment by Tungsteno74** [comment]
Thanks @kived . I'm not very able with kivy config (i'm still learning it)
But there is a fast fix for setup Android back button as esc in an app?

**Comment by kived** [comment]
The Android Back button should be keycode 4 instead of 27, try that. If nothing else, you can always have your keyboard callback method print the received keycodes. Then load your app, and press the back button - whatever prints out is what you need to look for. Either way, when you have that set up you can go back a screen when the back button is pressed, or exit your app if there's nowhere to go back.

**Comment by Tungsteno74** [comment]
Ok thanks! this fix the problem.

**Comment by kived** [comment]
Fixed in kivy/kivy#4207
