### ISSUE TITLE
Rotation Lock Ignored

### ISSUE THREAD

**Issue by FluxIX** [kivy/python-for-android#842]
I have a Kivy app with is ignoring the device's rotation lock. The app was built to be compatible with both portrait and landscape modes, but when the device has locked the orientation to either portrait or landscape, the application is able to display in either portrait or landscape orientation.
##

**Comment by inclement** [comment]
How did you set the rotation lock? With pyjnius?

**Comment by FluxIX** [comment]
The rotation lock was set through the devices settings, external to the app.

**Comment by KeyWeeUsr** [comment]
If the p4a doesn't check for orientation through spme java class(e.g. only by hardware changes - real rotation), it might ignore whole rotation lock mechanism that some of these apps use.

**Comment by rafalo1333** [comment]
I can confirm. Kivy apps are ignoring the global system setting which is annoying.

**Comment by inclement** [comment]
It turns out this is just because the correct setting is `--orientation=user` rather than `--orientation=sensor` - the former is the same, except that it obeys the user's rotation settings. Other options are also available, listed in the [Android documentation](https://developer.android.com/guide/topics/manifest/activity-element.html) under `android:screenOrientation`. I've added this information to the documentation.
