### ISSUE TITLE
The Kivy Option "softinput_mode" does not work on Android with bootstrap=sdl2

### ISSUE THREAD

**Issue by mrhdias** [kivy/python-for-android#847]
The Kivy Option "softinput_mode" does not work on Android with bootstrap=sdl2. I have successfully used the same code on Android with pygame.

**Comment by mrhdias** [comment]
https://github.com/kivy/kivy/blob/master/kivy/core/window/__init__.py

Perhaps the problem is in following code snippet:
```
    def _get_android_kheight(self):
        if USE_SDL2:  # Placeholder until the SDL2 bootstrap supports this
            return 0
        global android
        if not android:
            import android
        return android.get_keyboard_height()
```

**Comment by inclement** [comment]
Yep, that's the problem.

**Comment by mrhdias** [comment]
I commented the code and build the app again, but I get the following error:
ImportError: No module named android
```
    def _get_android_kheight(self):
        # if USE_SDL2:  # Placeholder until the SDL2 bootstrap supports this
        #    return 0
        global android
        if not android:
            import android
        return android.get_keyboard_height()
```

**Comment by inclement** [comment]
To fix this error, you'd need to add the android module to the
requirements. It is optional with SDL2, not built automatically as before.

However, the android module does not itself have code for this that will
work with SDL2. You would need to add this to the PythonActivity java
code, and ideally call it from Kivy with pyjnius rather than the android
module (which we'd rather keep optioal).

**Comment by rafalo1333** [comment]
Any updates on this issue?

**Comment by inclement** [comment]
I think qua-non has been working on it.

**Comment by inclement** [comment]
Fixed by https://github.com/kivy/kivy/pull/4665
