### ISSUE TITLE
AndroidBrowser.open() should return a value

### ISSUE THREAD

**Issue by WillDHB** [kivy/python-for-android#855]
The webbrowser.open() method and its variants expect the open methods of browsers to return a True value if the operation is successful, and a False value otherwise.

Presently, the AndroidBrowser does not return a value for these methods, causing webbrowser.open() to return False, indicating failure.

**Comment by inclement** [comment]
I've made these functions return True (https://github.com/kivy/python-for-android/commit/61b95b63e5bb7b62f3094ce48b7266b676413633). Right now there's no way to return False, but I'm not sure what even happens if this fails (all we know is that we asked the system to opena browser), so I guess it's okay for now.

If anyone has a better idea, such a contribution would be welcome.

Thanks for pointing this out.
