### ISSUE TITLE
plyer requirement does not work with ==master version

### ISSUE THREAD

**Issue by rafalo1333** [kivy/python-for-android#879]
The plyer's recipe makes it impossible to fetch master branch of the package. One needs to use git+url syntax as requirement.

**Comment by AndreMiras** [comment]
That's a rather old bug report :grimacing: 
We don't have a plyer recipe, do we? :thinking: 
Since we don't have recipe, it will be handled as a normal pip package and you can provide the full path to the zip archive including branch name for instance.
Feel free to reopen providing more details if you think I misunderstood.
