### ISSUE TITLE
[launcher] app update by http(s) from external website (https:// for github required)

### ISSUE THREAD

**Issue by ponyatov** [kivy/python-for-android#931]
Please add to KL TODO (feature request) :
add update/reload function for application over http (and https:// for github required)
to make apps update directly from smartphone

This have no sequrity risks so this function must be available only for already installed apps
(some update_url=https://github.com/user/app in adroid.txt config),
and using https:// for apps hosted on github gives some protection.

**Comment by inclement** [comment]
I don't think we'll be focusing on adding this functionality to python-for-android. We might consider an optional function for it if you'd like to make a PR, although it would be more ideal to make it possible to plug into the java code somehow so that users can do this without modifying python-for-android itself.

You can also do this from within a Python app using the normal Python modules.
