### ISSUE TITLE
[launcher] icon= and splash= parameters

### ISSUE THREAD

**Issue by ponyatov** [kivy/python-for-android#932]
feature request: 
1) show app icon in left side of kivy launcher apps list
icon=logo.png
2) show custom app bootup image, some meta info from author= title= copyright= ... , and content of bootup.txt file (app can write some useful info into this file to show on next boot up)
splash=splash.png

**Comment by inclement** [comment]
If people would like to contribute these things we would probably be happy to include them, but it's unlikely that any core developers will focus on them as we're more focused on the packaging aspects of python-for-android.

The launcher should perhaps ideally be a separate app that can attract its own development. I have in mind to try this at some point.

**Comment by KeyWeeUsr** [comment]
@ponyatov app icon is used, you only need to name a file `icon.png` and let it be in square shape. Custom splash is a nice idea, but it'll surely require Java code, because the launcher apk already has a default presplash, which is not accessible from outside (it's in `.apk` file). However, it's important to notice that the launcher is there for _editing and testing_ and not for _deploying_ apps, because it's very limited.
