### ISSUE TITLE
Could not ping localhost:5000

### ISSUE THREAD

**Issue by caaarlos** [kivy/python-for-android#960]
`25908 25953 V WebViewLoader: Could not ping localhost:5000`

**Comment by inclement** [comment]
The webview bootstrap repeatedly pings localhost until it becomes available (logging this message whenever the ping fails). As such, this is not a bug.

If you have a different problem, e.g. the pinging never works, please open a new issue with the full details of your build and the logcat log. Before doing so, check the log for python tracebacks - the most likely cause of this problem is that the python process crashes.

**Comment by caaarlos** [comment]
inclement, I'm sorry, I accidentally hit the post button, before I finished my post's writing.
