### ISSUE TITLE
"Could not remove android presplash" if 'android' is not in requirements

### ISSUE THREAD

**Issue by germn** [kivy/python-for-android#963]
If we use new toolchain we can see this message:

> [ERROR ] Base: Could not remove android presplash

It comes from [recent commit](https://github.com/kivy/kivy/commit/2d5b365747284b029c8a2b3291ca0f4d580e7b86) and happens if `android` is not in requirements.

I think this should be fixed, shouldn't it?

I see two possible ways:
- add `android` as mandatory dependency for new toolchain
- remove `remove_presplash` func [from](https://github.com/kivy/python-for-android/pull/930/commits/dbdc5158a7a077b589c5313b7ada135aa0f1084c) android module if it's possible

I don't know which one of ways is better.

**Comment by KeyWeeUsr** [comment]
You can read reasons for that in [IRC history](https://botbot.me/freenode/kivy-dev/2016-11-18/?msg=76701431&page=1). However, I'm not sure if `android` will be included or not as a requirement in toolchain. It's not an issue though, because the behavior before was just presplash displaying for a certain amount of time - it didn't disappear if the app was already successfully running.

For `pyjnius` and maybe even for `plyer` if on android it most likely should be included as a package, but by default I don't think so.

**Comment by germn** [comment]
@KeyWeeUsr thanks for answers. I agree that this and [second one](https://github.com/kivy/python-for-android/issues/962) issues doesn't affect app behavior, but I think it can be kept in tracker since non of them documented anywhere and it can be difficult to spit this messages from problems that can happen ([for example](https://github.com/kivy/python-for-android/issues/658#issuecomment-242340732)). 

I mean, it would save me lot of time if I could find all written here in google earlier.

**Comment by KeyWeeUsr** [comment]
Closed by https://github.com/kivy/kivy/commit/c72ce62a7cbf5c4c3015a7035fac0312f43b097f
