### ISSUE TITLE
Error with permission specification via setup.cfg

### ISSUE THREAD

**Issue by nlopez73** [kivy/python-for-android#985]
I'm using setup.cfg to specify multiple permissions for my app, but only the last one  is written on distribution's AndroidManifest.xml file.
I think this is expected behavior, but it don't let us to specify app options via setup.cfg fully.
I'm working with master brach.
Thanks!!

**Comment by KeyWeeUsr** [comment]
I presume you're using the `setup.py` option for distributing your app. See [sdl2.py](https://github.com/kivy/python-for-android/blob/master/testapps/testlauncher_setup/sdl2.py#L16) for this. I'm not sure how well does it work for console arguments e.g.:

    --permission INTERNET,SOMETHING,ELSE

because that's a little bit different [code](https://github.com/kivy/python-for-android/blob/master/pythonforandroid/bdistapk.py#L46). Maybe using just a single string:

    'permission': 'INTERNET,SOMETHING,ELSE'

in the options could do the trick. A useful thing could be also sharing the code/config :)

**Comment by nlopez73** [comment]
Yes, I'm using setup.py and i'm trying to specify options using a setup.cfg file like that,
[setup.cfg.zip](https://github.com/kivy/python-for-android/files/711117/setup.cfg.zip)

**Comment by KeyWeeUsr** [comment]
Add the "s" if you can use lists in the .cfg files

    permissions=['INTERNET', 'ACCESS_NETWORK_STATE', ...

and use only a single keyword. I'm not sure if you can. If not, then use try the previously mentioned

    permission=INTERNET,ACCESS_NETWORK_STATE, ...

it should trigger the p4a command line arg parser.

**Comment by nlopez73** [comment]
Finally i used options dictionary in setup.py,  permissions in setup.cfg don't work right.

Thanks a lot

**Comment by inclement** [comment]
@nlopez73 Thanks for the report, I'm intending to make some changes to this argument to resolve these problems and make setup.cfg properly usable.

**Comment by Julian-O** [comment]
Closing as solved.
